
e2e_test:
  image: cypress/included:14.2.0
  stage: e2e_test
  before_script:
    - cd Frontend/DAT251-frontend
  script:
    - npx cypress run --config "baseUrl=http://localhost:5173" --headless

  tags:
    - docker
