stages:
  - setup
  - test
  - build

# Setup Stage - Install dependencies and check environment
setup_backend:
  image: maven:3.9.6-eclipse-temurin-21
  stage: setup
  script:
    - cd backend
    - mvn --version
    - mvn validate
    - echo "Backend setup complete"

setup_frontend:
  image: node:20
  stage: setup
  script:
    - cd frontend  # Navigate to the frontend folder
    - node -v
    - npm install 
    - npm run check  
    - echo "Frontend setup complete"

# Test Stage - Run tests to ensure everything works
test_backend:
  image: maven:3.9.6-eclipse-temurin-21
  stage: test
  script:
    - cd backend
    - mvn test
    - echo "Backend tests complete"
  tags:
    - docker

test_frontend:
  image: node:20
  stage: test
  script:
    - cd frontend  # Navigate to the frontend folder
    - npm run test   # Run frontend tests
    - echo "Frontend tests complete"
  tags:
    - docker

# Build Stage - Compile and prepare project for deployment
build_backend:
  image: maven:3.9.6-eclipse-temurin-21
  stage: build
  script:
    - cd backend
    - mvn compile
    - echo "Backend build complete"
  tags:
    - shell

build_frontend:
  image: node:20
  stage: build
  script:
    - cd frontend  # Navigate to the frontend folder
    - npm run build  # Build for production or prepare for deployment
    - echo "Frontend build complete"
  tags:
    - shell
