stages:
  - test
  - build

# Backend Test
test_backend:
  image: maven:3.9.6-eclipse-temurin-21
  stage: test
  script:
    - cd backend/Gallery
    - mvn validate  # Validate the backend before testing
    - mvn test  # Run backend unit tests
    - mvn verify  # Ensure all tests pass
    - echo "Backend tests complete"
  tags:
    - docker

# Frontend Test
test_frontend:
  image: node:20
  stage: test
  script:
    - cd frontend
    - npm install  # Install frontend dependencies
    - npm run test  # Run frontend unit tests
    - npm run coverage  # Check test coverage
    - echo "Frontend tests complete"
  tags:
    - docker

# Backend Build
build_backend:
  image: maven:3.9.6-eclipse-temurin-21
  stage: build
  script:
    - cd backend/Gallery
    - mvn compile
    - mvn package  # Create a deployable package (e.g., JAR)
    - echo "Backend build complete"
  tags:
    - docker

# Frontend Build
build_frontend:
  image: node:20
  stage: build
  script:
    - cd frontend
    - npm install  # Ensure frontend dependencies are installed
    - npm run build  # Build the frontend
    - echo "Frontend build complete"
  tags:
    - docker
