stages:
  - test_and_build
  - e2e_test


test_and_build_backend:
  image: maven:3.9.6-eclipse-temurin-21
  stage: test_and_build
  before_script:
    - cd backend/Gallery
  script:
    - mvn validate  # Validate the backend before testing
    - mvn test  # Run backend unit tests
    - mvn verify  # Ensure all tests pass
    - mvn package  # Build the backend (create JAR file)
    - echo "Backend test and build complete"
  tags:
    - docker
  

test_and_build_frontend:
  image: node:20
  stage: test_and_build
  before_script:
    - cd Frontend/DAT251-frontend
  script:
    - npm install  # Install frontend dependencies (only once)
    - npm run test  # Run frontend unit tests
    - npm run coverage  # Check test coverage
    - npm run build  # Build the frontend
    - echo "Frontend test and build complete"
  tags:
    - docker


  e2e_test:
    stage: e2e_test
    image: node:20
    stage: test
    before_script:
      - cd Frontend/DAT251-frontend
    script:
      - npx cypress run --headless # Run Cypress tests
    tags:
      - docker
