stages:
  - test_and_build
  - e2e_test

test_and_build_backend:
  image: maven:3.9.6-eclipse-temurin-21-alpine
  stage: test_and_build
  before_script:
    - cd backend/Gallery
  script:
    - export MAVEN_OPTS="-Xmx1024m -Xms512m"
    - mvn clean test package
    - echo "Backend test and build complete"
  tags:
    - docker
  cache:
    key: maven
    paths:
      - /root/.m2/repository

test_and_build_frontend:
  image: node:20
  stage: test_and_build
  before_script:
    - cd Frontend/DAT251-frontend
  script:
    - npm ci  # Ensure a clean dependency installation
    - npm run build  # Build the frontend
    - echo "Frontend test and build complete"
  tags:
    - docker
  cache:
    key: frontend
    paths:
      - Frontend/DAT251-frontend/node_modules/

e2e_test:
  image: cypress/included:14.2.0
  stage: e2e_test
  script:
    - cd backend/Gallery
    - setsid ./mvnw spring-boot:run > backend.log 2>&1 &
    - cd ../../Frontend/DAT251-frontend
    - npm install -g serve
    - nohup serve -s build -l 5173 > frontend.log 2>&1 &
    - npx wait-on http://localhost:8080 http://localhost:5173
    - /bin/sh -c "npx cypress run --config 'baseUrl=http://localhost:5173' --headless"
  tags:
    - docker
